#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2025 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.3.4
# Product:       stc42
# Model-Version: 1.0.0
#

import argparse
import time
from sensirion_i2c_driver import LinuxI2cTransceiver, I2cConnection, CrcCalculator
from sensirion_driver_adapters.i2c_adapter.i2c_channel import I2cChannel
from sensirion_i2c_stc42.device import Stc42Device

parser = argparse.ArgumentParser()
parser.add_argument('--i2c-port', '-p', default='/dev/i2c-1')
args = parser.parse_args()

with LinuxI2cTransceiver(args.i2c_port) as i2c_transceiver:
    channel = I2cChannel(I2cConnection(i2c_transceiver),
                         slave_address=0x29,
                         crc=CrcCalculator(8, 0x31, 0xff, 0x0))
    sensor = Stc42Device(channel)
    try:
        sensor.stop_measurement()
        (product_number, serial_number
         ) = sensor.read_product_info()
        print(f"product_number: {product_number}; "
              f"serial_number: {serial_number}; "
              )
        time.sleep(0.01)
    except BaseException:
        ...
    sensor.compensate_humidity_with_sht4x()
    sensor.compensate_temperature_with_sht4x()
    sensor.start_concentration_measurement(1000)
    time.sleep(0.1)
    for i in range(50):
        try:
            time.sleep(1.0)
            (hydrogen, temperature, humidity, ambient_pressure, error_flags
             ) = sensor.read_measurements()
            print(f"hydrogen: {hydrogen}; "
                  f"temperature: {temperature}; "
                  f"humidity: {humidity}; "
                  f"ambient_pressure: {ambient_pressure}; "
                  f"error_flags: {error_flags}; "
                  )
        except BaseException:
            continue
    sensor.stop_measurement()
